replicaCount: 1

image:
  repository: harbey271/employee-management-api
  pullPolicy: IfNotPresent
  tag: "97fc627cf84e394d53f64ba066668f66020109f3"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: employee-management.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - employee-management.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /health
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

frontend:
  enabled: true
  replicaCount: 1

  image:
    repository: harbey271/employee-management-frontend
    pullPolicy: Always
    tag: "latest"

  service:
    port: 80
